#default: &default
#  adapter: sqlite3
#  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost
  pool: 5

#development:
# <<: *default
#  database: storage/development.sqlite3

development:
  <<: *default
  database: sona_development

#test:
#  <<: *default
#  database: storage/test.sqlite3

test:
  <<: *default
  database: sona_test

#production:
#  primary:
#    <<: *default
#    database: storage/production.sqlite3
#  cache:
#    <<: *default
#    database: storage/production_cache.sqlite3
#    migrations_paths: db/cache_migrate
#  queue:
#    <<: *default
#    database: storage/production_queue.sqlite3
#    migrations_paths: db/queue_migrate
#  cable:
#    <<: *default
#    database: storage/production_cable.sqlite3
#    migrations_paths: db/cable_migrate

production:
  <<: *default
  database: sona_production
  username: sona
  password: <senha>
